import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AppProvider } from "./context/AppContext";
import { cookies } from "next/headers";
import { APP_ACCESS_TOKEN_KEY } from "@/data/http";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(APP_ACCESS_TOKEN_KEY)?.value ?? null;

  console.log('TOKEN===', token);
  

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AppProvider>
          <nav className="fixed top-0 left-0 w-full z-50 border-b border-white/10">
            <ul className="flex items-center gap-6 px-6 py-4 max-w-2xl mx-auto">
              <li>
                <Link href="/" className="text-white font-medium text-sm hover:opacity-75 transition-opacity">
                  Home
                </Link>
              </li>
            </ul>
          </nav>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
