import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AppProvider } from "./context/AppContext";
import { cookies } from "next/headers";
import { APP_ACCESS_TOKEN_KEY } from "@/data/http";
import { UserService } from "@/data/services/user.service";
import { Navbar } from "./components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(APP_ACCESS_TOKEN_KEY)?.value ?? '';

  // console.log('TOKEN===', token);

  // UserService.getServerUserInfo(token).then((res) => {
  //   console.log('RESS', res);
    
  // })
  

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AppProvider>
          <Navbar />
          
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
