import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791026043573 implements MigrationInterface {
    name = 'InitialSchema1791026043573'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Baseline of the schema previously maintained by hand in query.sql.
        // Existing databases already have these tables: just record the migration as run.
        if (await queryRunner.hasTable('users')) return;

        await queryRunner.query(`CREATE TABLE "user_answers" ("id" SERIAL NOT NULL, "user_id" integer, "question_id" integer, "answer_id" integer, "is_correct" boolean, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "session_id" integer, CONSTRAINT "PK_08977c1a2a5f1b8b472dbd87d04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."book_lessons_lesson_type_enum" AS ENUM('text', 'video', 'quiz', 'assignment', 'file')`);
        await queryRunner.query(`CREATE TABLE "book_lessons" ("id" SERIAL NOT NULL, "book_id" integer NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "content" text, "lesson_type" "public"."book_lessons_lesson_type_enum" NOT NULL DEFAULT 'text', "media_url" text, "order_index" integer NOT NULL DEFAULT '0', "is_free_preview" boolean NOT NULL DEFAULT false, "estimated_minutes" integer, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6ec0b417e610a4035442a22f400" UNIQUE ("book_id", "slug"), CONSTRAINT "PK_20ef6c0246ea1b8758f164e8aa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."books_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TABLE "books" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "book_url" character varying(255), "description" text, "cover_image_url" text, "status" "public"."books_status_enum" NOT NULL DEFAULT 'draft', "is_public" boolean NOT NULL DEFAULT true, "created_by" integer, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4dc5a40933419641440fbd95e8e" UNIQUE ("slug"), CONSTRAINT "PK_f3f2f25a099d24e12545b70b022" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book_topics" ("id" BIGSERIAL NOT NULL, "book_id" integer NOT NULL, "topic_id" integer NOT NULL, CONSTRAINT "UQ_cef952db92aeadc24cf15ea43dd" UNIQUE ("book_id", "topic_id"), CONSTRAINT "PK_53af3ab5134cb704e59a53d925a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "topics" ("id" SERIAL NOT NULL, "category_id" integer, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e4aa99a3fa60ec3a37d1fc4e853" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("id" SERIAL NOT NULL, "question_id" integer NOT NULL, "content" text NOT NULL, "is_correct" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9c32cec6c71e06da0254f2226c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grades" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "code" character varying(50) NOT NULL, "sort_order" integer NOT NULL, CONSTRAINT "UQ_aed8f750101d1f10aa3d6f78024" UNIQUE ("code"), CONSTRAINT "PK_4740fb6f5df2505a48649f1687b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" SERIAL NOT NULL, "tenant_id" bigint, "content" text NOT NULL, "image_url" text, "explanation" text, "type" character varying(50) NOT NULL, "difficulty" character varying(50), "category_id" integer, "topic_id" bigint, "grade_id" integer, "code" jsonb, "created_by" bigint, "is_active" boolean NOT NULL DEFAULT true, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quizzes" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "category_id" integer, "topic_id" integer, "duration_minutes" integer, "total_questions" integer, "quiz_type" character varying(255), "status" character varying(255), "created_by" integer, "grade_id" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b24f0f7662cf6b3a0e7dba0a1b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz_sessions" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "quiz_id" integer NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'in_progress', "score" integer NOT NULL DEFAULT '0', "total_questions" integer, "correct_answers" integer, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "end_time" TIMESTAMP WITH TIME ZONE, "due_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_db4ac35661dd2f29269b272a4c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schedule_users" ("id" SERIAL NOT NULL, "schedule_id" integer NOT NULL, "user_id" integer NOT NULL, "role" character varying(50) NOT NULL, "attendance_status" character varying(50) NOT NULL DEFAULT 'pending', "is_required" boolean NOT NULL DEFAULT true, "response_at" TIMESTAMP, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_213eea87d96157a2dbb5531a01b" UNIQUE ("schedule_id", "user_id"), CONSTRAINT "PK_39ac17090e5af823506f98a1ba0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" SERIAL NOT NULL, "tenant_id" bigint, "class_id" integer, "created_by" integer NOT NULL, "title" character varying NOT NULL, "description" text, "note" text, "scope" character varying(50) NOT NULL DEFAULT 'personal', "schedule_type" character varying(50) NOT NULL DEFAULT 'event', "status" character varying(50) NOT NULL DEFAULT 'scheduled', "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_plan_type_enum" AS ENUM('free', 'pro', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_status_enum" AS ENUM('active', 'suspended', 'deleted')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" BIGSERIAL NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(100) NOT NULL, "description" text, "domain" character varying(255), "custom_domain" character varying(255), "logo_url" text, "favicon_url" text, "primary_color" character varying(20), "secondary_color" character varying(20), "owner_user_id" integer, "organization_id" bigint, "plan_type" "public"."tenants_plan_type_enum" NOT NULL DEFAULT 'free', "max_users" integer NOT NULL DEFAULT '100', "max_storage_mb" integer NOT NULL DEFAULT '1024', "is_paid" boolean NOT NULL DEFAULT false, "status" "public"."tenants_status_enum" NOT NULL DEFAULT 'active', "is_active" boolean NOT NULL DEFAULT true, "settings" jsonb, "require_2fa" boolean NOT NULL DEFAULT false, "allowed_ips" text array, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_3021c18db2b363ae9324c826c5a" UNIQUE ("code"), CONSTRAINT "REL_9b0b65d017f95fd4e7e3576bad" UNIQUE ("owner_user_id"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3021c18db2b363ae9324c826c5" ON "tenants" ("code") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying, "role" text, "tenant_id" bigint, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_members" ("id" SERIAL NOT NULL, "class_id" integer NOT NULL, "student_id" integer NOT NULL, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(50) NOT NULL DEFAULT 'active', "role" character varying(50) NOT NULL DEFAULT 'student', CONSTRAINT "UQ_a86e55ca8dcab99e2245cda6e17" UNIQUE ("class_id", "student_id"), CONSTRAINT "PK_c06d2c3bc732509dcbbab8d5730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" SERIAL NOT NULL, "tenant_id" bigint, "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "description" text, "teacher_id" integer NOT NULL, "grade_id" integer, "school_name" character varying(255), "status" character varying(50) NOT NULL DEFAULT 'active', "created_by" bigint, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cf7491878e0fca8599438629988" UNIQUE ("code"), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_subjects" ("id" SERIAL NOT NULL, "class_id" integer NOT NULL, "subject_id" integer NOT NULL, "teacher_id" integer, "status" character varying(20) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bd863400a0b317b7e43118a970b" UNIQUE ("class_id", "subject_id"), CONSTRAINT "PK_4e1ecabd8771166a29291dc09ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(50), "description" text, "status" character varying(20) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_542cbba74dde3c82ab49c573109" UNIQUE ("code"), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "learning_activities" ("id" BIGSERIAL NOT NULL, "lesson_id" integer NOT NULL, "activity_type" character varying(50) NOT NULL, "instruction" text NOT NULL, "config" jsonb NOT NULL, "order_index" integer NOT NULL DEFAULT '0', "points" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_08f382df9941949266184557458" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "content" text, "subject_id" integer, "topic_id" integer, "grade_id" integer, "created_by" integer NOT NULL, "lesson_type" character varying(50) NOT NULL DEFAULT 'text', "visibility" character varying(50) NOT NULL DEFAULT 'private', "status" character varying(50) NOT NULL DEFAULT 'draft', "thumbnail_url" text, "media_url" text, "estimated_minutes" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_vocabularies" ("id" BIGSERIAL NOT NULL, "lesson_id" integer NOT NULL, "vocabulary_id" bigint NOT NULL, "order_index" integer NOT NULL DEFAULT '0', CONSTRAINT "lesson_vocabularies_lesson_vocab_unique" UNIQUE ("lesson_id", "vocabulary_id"), CONSTRAINT "PK_ea1806eca5d7ee3441620af210e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0753a8ba06b815d160412acc33" ON "lesson_vocabularies" ("lesson_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_28955125ff0b01c2e4e01bef3f" ON "lesson_vocabularies" ("vocabulary_id") `);
        await queryRunner.query(`CREATE TABLE "vocabularies" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint, "word" character varying(255) NOT NULL, "pinyin" character varying(255), "han_viet" character varying(255), "meaning_vi" character varying(255), "meaning_en" character varying(255), "example_sentence" character varying(255), "audio_url" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1f0c8d5539ccaf456ebf73cabb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b05ca6fd3f7da4f2e29690612" ON "vocabularies" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."pages_status_enum" AS ENUM('draft', 'published')`);
        await queryRunner.query(`CREATE TABLE "pages" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "content" text NOT NULL, "status" "public"."pages_status_enum" NOT NULL DEFAULT 'draft', "meta_title" character varying(255), "meta_description" text, "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe66ca6a86dc94233e5d7789535" UNIQUE ("slug"), CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content_audios" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "content_id" integer NOT NULL, "provider" character varying(50) NOT NULL DEFAULT 'elevenlabs', "voice_id" character varying(255), "model_id" character varying(255), "audio_url" text NOT NULL, "mime_type" character varying(100) NOT NULL DEFAULT 'audio/mpeg', "duration_seconds" integer, "file_size_bytes" bigint, "text_hash" character varying(128) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'completed', "error_message" text, "settings" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7c762897234cc039873384088c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "learning_contents" ("id" SERIAL NOT NULL, "tenant_id" integer NOT NULL, "user_id" integer, "lesson_id" integer, "title" character varying(255), "content" text NOT NULL, "type" character varying(50) NOT NULL, "language_code" character varying(20) NOT NULL, "level" character varying(50), "created_by_ai" boolean NOT NULL DEFAULT false, "prompt" text, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1070bbbf106fdcc9264046863c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."courses_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."courses_visibility_enum" AS ENUM('private', 'public', 'school_only')`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint, "title" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "language_code" character varying(20), "subject_code" character varying(100), "level_code" character varying(100), "thumbnail_url" text, "cover_url" text, "status" "public"."courses_status_enum" NOT NULL DEFAULT 'draft', "visibility" "public"."courses_visibility_enum" NOT NULL DEFAULT 'private', "order_index" integer NOT NULL DEFAULT '0', "created_by" bigint, "updated_by" bigint, "published_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "courses_slug_unique_per_tenant" UNIQUE ("tenant_id", "slug"), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d08a72c4c2359e5ab814205811" ON "courses" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3dc725fda2e77b01776d1a801e" ON "courses" ("language_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_6299d3fabbe5e51c7387578cb3" ON "courses" ("subject_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."course_modules_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TABLE "course_modules" ("id" BIGSERIAL NOT NULL, "course_id" bigint NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "order_index" integer NOT NULL DEFAULT '0', "status" "public"."course_modules_status_enum" NOT NULL DEFAULT 'draft', "created_by" bigint, "updated_by" bigint, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "course_modules_slug_unique_per_course" UNIQUE ("course_id", "slug"), CONSTRAINT "PK_4c195db0718e8845a6e09075ebc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81644557c2401f37fe9e884e88" ON "course_modules" ("course_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec832169b9c20c9485bd61c654" ON "course_modules" ("status") `);
        await queryRunner.query(`CREATE TABLE "course_module_lessons" ("id" BIGSERIAL NOT NULL, "course_module_id" bigint NOT NULL, "lesson_id" integer NOT NULL, "order_index" integer NOT NULL DEFAULT '0', "is_preview" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "course_module_lessons_unique" UNIQUE ("course_module_id", "lesson_id"), CONSTRAINT "PK_a9fed5af938e7daf885b2b33194" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4bced407bedde3e4e049f43c96" ON "course_module_lessons" ("course_module_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5fb9287976555d89dcaa16d2e" ON "course_module_lessons" ("lesson_id") `);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "class_subject_id" integer NOT NULL, "lesson_id" integer, "quiz_id" integer, "assigned_by" integer NOT NULL, "start_at" TIMESTAMP WITH TIME ZONE, "due_at" TIMESTAMP WITH TIME ZONE, "max_attempts" integer NOT NULL DEFAULT '1', "total_points" integer NOT NULL DEFAULT '0', "assignment_type" character varying(50) NOT NULL DEFAULT 'quiz', "status" character varying(50) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assignment_comments" ("id" SERIAL NOT NULL, "assignment_student_id" integer NOT NULL, "user_id" integer NOT NULL, "content" text NOT NULL, "parent_id" integer, "status" character varying(20) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_99976f728e0bca8642be0f2bec7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assignment_students" ("id" SERIAL NOT NULL, "assignment_id" integer NOT NULL, "student_id" integer NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'assigned', "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "feedback" text, "started_at" TIMESTAMP WITH TIME ZONE, "submitted_at" TIMESTAMP WITH TIME ZONE, "score" integer NOT NULL DEFAULT '0', "attempt_count" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_4ed08d6eaccb8a2b1f544907902" UNIQUE ("assignment_id", "student_id"), CONSTRAINT "PK_e19467585f4f32d27d3e9dad63b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_b1dae489bd29735481f300ae311" FOREIGN KEY ("session_id") REFERENCES "quiz_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_lessons" ADD CONSTRAINT "FK_871a98728535837d3859b64b08d" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_92606f78a31e625fe1ba164c815" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_topics" ADD CONSTRAINT "FK_4b338b9152212a71618b65260eb" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_topics" ADD CONSTRAINT "FK_791418dcf9a37c400233471f568" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "FK_55f03ccaeee22a418c4b00b83a2" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_677120094cf6d3f12df0b9dc5d3" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_72285dafbbddab344676a6a4b7a" FOREIGN KEY ("grade_id") REFERENCES "grades"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_6004e23393f2a8efe414480b75d" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes" ADD CONSTRAINT "FK_fe614b824b1dc21d87979e1ce36" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes" ADD CONSTRAINT "FK_f9e23f0ec70c755515c8a394923" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes" ADD CONSTRAINT "FK_ee1627e12c588f5a40792b13e68" FOREIGN KEY ("grade_id") REFERENCES "grades"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_sessions" ADD CONSTRAINT "FK_b800b1dc82988f43429fc276e6f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_sessions" ADD CONSTRAINT "FK_7d5e2cc965658e66690ca6533cd" FOREIGN KEY ("quiz_id") REFERENCES "quizzes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_users" ADD CONSTRAINT "FK_55634b72855b44903452ed75486" FOREIGN KEY ("schedule_id") REFERENCES "schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_users" ADD CONSTRAINT "FK_eef76312193002358d91ee5808d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_419857fc68975b6df572ad288d1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_96d9e884d615df87013aefbdf21" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_c586acbf0fb865568c014a7a0b0" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_9b0b65d017f95fd4e7e3576bad4" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_members" ADD CONSTRAINT "FK_2ace5ca20caf6953506af45c935" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_members" ADD CONSTRAINT "FK_0afbf47de031aa2347b3fd659f6" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_80e98e9a9146352f155f0bd3ade" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_b34c92e413c4debb6e0f23fed46" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_subjects" ADD CONSTRAINT "FK_433f93dd22b685e59c285726a1f" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_subjects" ADD CONSTRAINT "FK_9d8971acdcc64a1703357a00759" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_subjects" ADD CONSTRAINT "FK_f1406cab45041349673d6887aed" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_activities" ADD CONSTRAINT "FK_82bc5c2191123861d2ff5a6941b" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_0a4d6534fe0b7cd9470041389cb" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_1dc6a3509df72e37a9282f67965" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_b0b03e1a2a508a2b338138fbec0" FOREIGN KEY ("grade_id") REFERENCES "grades"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_b96adc7c3e06624edae3e0a01ae" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_vocabularies" ADD CONSTRAINT "FK_0753a8ba06b815d160412acc33a" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_vocabularies" ADD CONSTRAINT "FK_28955125ff0b01c2e4e01bef3f7" FOREIGN KEY ("vocabulary_id") REFERENCES "vocabularies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_064ab67bb29a28d073db287fc6d" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_audios" ADD CONSTRAINT "FK_dd4e51a5574551493197154fd14" FOREIGN KEY ("content_id") REFERENCES "learning_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_modules" ADD CONSTRAINT "FK_81644557c2401f37fe9e884e884" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_module_lessons" ADD CONSTRAINT "FK_4bced407bedde3e4e049f43c961" FOREIGN KEY ("course_module_id") REFERENCES "course_modules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_module_lessons" ADD CONSTRAINT "FK_a5fb9287976555d89dcaa16d2e1" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_17e9a4319c7fb8ae84a90a610f0" FOREIGN KEY ("class_subject_id") REFERENCES "class_subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_c0fda9de424e0e719787f6b5764" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_2c6ad39dcb44b06bf8a61711460" FOREIGN KEY ("quiz_id") REFERENCES "quizzes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_9791cf4f0e9b9a77ca09f1d4b0f" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_comments" ADD CONSTRAINT "FK_5eca6f39ee6497c31130a1c39c9" FOREIGN KEY ("assignment_student_id") REFERENCES "assignment_students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_comments" ADD CONSTRAINT "FK_9ced56f8f5395cb97cd03a11883" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_comments" ADD CONSTRAINT "FK_1d161b15b8c0427a46781a5e2f8" FOREIGN KEY ("parent_id") REFERENCES "assignment_comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_students" ADD CONSTRAINT "FK_20a008bc7c14483397379dd915a" FOREIGN KEY ("assignment_id") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_students" ADD CONSTRAINT "FK_d2fdf0de34d3236be545e10c111" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(_queryRunner: QueryRunner): Promise<void> {
        // Reverting the baseline would drop every table. Do it by hand if you really mean it.
        throw new Error('InitialSchema baseline cannot be reverted');
    }

}
